// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVxJaLc6gSSfA0OctVJ4gRStno2MoAcU',
    appId: '1:897838614090:web:7efffc502f229accd448b3',
    messagingSenderId: '897838614090',
    projectId: 'ethosv2',
    authDomain: 'ethosv2.firebaseapp.com',
    storageBucket: 'ethosv2.appspot.com',
    measurementId: 'G-9T2F4ZWKMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JQmRepp0qTDH8dHzOu4o_fz4sh3ZA40',
    appId: '1:897838614090:android:806fc2b8826e7df2d448b3',
    messagingSenderId: '897838614090',
    projectId: 'ethosv2',
    storageBucket: 'ethosv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWi3kxW3mjrPEzeyqmfXIZB_Q0r_lWvZ8',
    appId: '1:897838614090:ios:90a4966d9bd10a4ad448b3',
    messagingSenderId: '897838614090',
    projectId: 'ethosv2',
    storageBucket: 'ethosv2.appspot.com',
    iosBundleId: 'com.quid.ethosv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWi3kxW3mjrPEzeyqmfXIZB_Q0r_lWvZ8',
    appId: '1:897838614090:ios:90a4966d9bd10a4ad448b3',
    messagingSenderId: '897838614090',
    projectId: 'ethosv2',
    storageBucket: 'ethosv2.appspot.com',
    iosBundleId: 'com.quid.ethosv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcVxJaLc6gSSfA0OctVJ4gRStno2MoAcU',
    appId: '1:897838614090:web:6439c182e4069b5dd448b3',
    messagingSenderId: '897838614090',
    projectId: 'ethosv2',
    authDomain: 'ethosv2.firebaseapp.com',
    storageBucket: 'ethosv2.appspot.com',
    measurementId: 'G-B54JZZB3X8',
  );
}
